#!/bin/bash
if [[ $BASH_SOURCE != $0 ]]; then echo "$BASH_SOURCE must be executed, not sourced."; return 255; fi

. idz_openssl_config.bash

function idz_error_check ()
{
  if [ $1 -ne 0 ]; then
    exit $1
  fi
}

mkdir -p $IDZ_OPENSSL_DIR
pushd $IDZ_OPENSSL_DIR > /dev/null

echo "Downloading $IDZ_OPENSSL_TAR"
curl -O $IDZ_OPENSSL_URL/$IDZ_OPENSSL_TAR
idz_error_check $?

echo "Downloading $IDZ_OPENSSL_MD5"
curl -O $IDZ_OPENSSL_URL/$IDZ_OPENSSL_MD5
idz_error_check $?

calculated_md5=$(md5 $IDZ_OPENSSL_TAR | cut -f 2 -d "=")
expected_md5=$(cat $IDZ_OPENSSL_MD5)
echo "MD5 check: (expected=$expected_md5 calculated=$calculated_md5)"
if [ $calculated_md5 != $expected_md5 ]; then 
  echo "MD5 check: FAIL (expected=$expected_md5 calculated=$calculated_md5)"
  exit 1
fi
echo "MD5 check: PASS"; 

echo "Decompressing $IDZ_OPENSSL_TAR"
tar xfz $IDZ_OPENSSL_TAR
idz_error_check $?
echo "Decompression complete."

popd > /dev/null

